#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:25:00
#PBS -N HCP ACPC Alignment
#PBS -V

module load singularity 2> /dev/null

singularity exec -e docker://brainlife/fsl:5.0.9 ./hcpAlignACPC.sh

if possible_error==1
    results.quality_check = 'ERROR: The following tracts failed:';
    results.failed_tracts = failed_tracts;
else
    results.quality_check = 'All tracts analysis profiles were created successfully';
fi

if [ ! -s t1.nii.gz ];
then
	echo "output missing"
	results="ERROR: ACPC Alignment failed with an error";
	cat <<EOM >product.json
	${results}
	EOM;
	exit 1
else
	cat <<EOM >product.json
	"ACPC Alignment complete"
	EOM;
fi

